engines:
  eslint:
    enabled: true
  fixme:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
  paths:
  - ./**/*
exclude_paths:
- subldir_1/foo.js